M48
; DRILL file {KiCad (6.0.6)} date Thu Jun 30 18:10:47 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-30T18:10:47+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X3.0224Y-2.0469
X3.9673Y-2.0469
T2
X2.7469Y-2.8343
X8.2587Y-3.1492
T0
M30
